project:
  type: website
  render:
   - "*.qmd"
   - "content/*.qmd"
   - "content/resurse/*.qmd"
   - "content/slides/*.qmd"
  resources:
    - "assets/"
  preview:
    port: 4200


website:
  title: ""
  page-navigation: true



  navbar:
    background: "#eee"
    foreground: "#000000"
    logo: "assets/imagini/logo.svg"
    left:
      - href: index.qmd
        text: Despre
      - href: content/00_agenda.qmd
        text: Workshop



  sidebar:
    - id: workshop
      style: docked
      type: light
      background: "#eee"
      foreground: dark
      contents:
        - content/00_agenda.qmd
        - content/01_introducere.qmd
        - content/02_provocari_si_riscuri.qmd
        - content/03_cadru_decizie.qmd
        - text: '<div class="sidebar-divider"><b>Resurse</b></div>'
        - content/resurse/arbore_decizie_ia.qmd
        - content/resurse/checklist_ia_responsabila.qmd
        - content/resurse/cadru_decizie_ia.qmd
        - text: '<div class="sidebar-divider"><b>Aplicații practice</b></div>'
        - content/aplicatii/scenariu_01_catalogare.qmd
        - content/aplicatii/scenariu_02_comunicare.qmd
        - content/aplicatii/scenariu_03_administrativ.qmd
        - content/aplicatii/scenariu_04_call_center.qmd
        - content/aplicatii/scenariu_05_suport_clienti.qmd
        - content/aplicatii/scenariu_06_educatie.qmd




  page-footer:
    left: |
      Conținut {{< fa brands creative-commons >}} 2025 Cozmina Secula
      <br>
      <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" style="text-decoration: none;">
        <img alt="Licență Creative Commons" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" style="vertical-align: middle;"/>
        Acest conținut este licențiat sub CC BY-NC-SA 4.0.
    right: |
      Website realizat cu {{< quarto >}} [Quarto](https://quarto.org/)


format:
  html:
    theme: [cosmo, brand, styles/_style.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_include/header.html"
    toc: true
    toc-title: "Pe această pagină"
    footnotes-hover: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem
