project:
  type: website

website:
  title: ""
  page-navigation: true



  navbar:
    background: "#eee"
    foreground: "#000000"
    logo: "assets/imagini/logo.svg"
    left:
      - href: index.qmd
        text: Despre
      - href: content/00_agenda.qmd
        text: Workshop
      - href: about.qmd
        text: Facilitator


  sidebar:
    - id: workshop
      style: docked
      type: light
      background: "#eee"
      foreground: dark
      contents:
        - content/00_agenda.qmd
        - content/01_introducere.qmd
        - content/02_provocari_si_riscuri.qmd
        - content/03_cadru_decizie.qmd
        - text: '<div class="sidebar-divider"><b>Resurse</b></div>'
        - content/resurse/arbore_decizie_ia.qmd
        - content/resurse/checklist_ia_responsabila.qmd




  page-footer:
    left: " Conținut {{< fa brands creative-commons >}} 2025 Cozmina Secula<br> Resursă sub licența [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/)."
    right: |
      Website realizat cu {{< quarto >}} [Quarto](https://quarto.org/)<br>

format:
  html:
    theme: [cosmo, brand, styles/_style.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_include/header.html"
    toc: true
    toc-title: "Pe această pagină"
    footnotes-hover: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem
