---
title: "<b>Fundamentele Inteligen탵ei Artificiale Generative</b>"
subtitle: "<b>C칙nd s캒 folose탳ti, c칙nd s캒 evi탵i 탳i<br> cum s캒 alegi instrumentele IA Generativ캒</b>"
format: html
toc: false
title-block-banner: true
title-block-style: default
---

```{=html}
<style>
.quarto-title-banner {
    color: #000;
    background-size: cover;
    background-position: center;
    height: 300px;
    transition: filter 15s;
}
.quarto-title {
    position: absolute;
    top: 2rem;
    left: 1.5rem;
    grid-column: unset !important;
}
.quarto-title > * {
    z-index: 1;
    position: relative;
}
.quarto-title-banner .quarto-title::before {
    position: absolute;
    inset: 0;
    content: "";
    z-index: 0;
}
.quarto-title-banner h1 {
    color: #000;
    font-weight: 600 !important;
    font-size: max(min(4vw, 2.5em), 1.8em);
    text-wrap: pretty;
}
.quarto-title-banner .subtitle {
    color: #000;
    font-size: max(min(3.5vw, 2em), 1.4em);
    font-weight: 400;
}
@media (max-width: 575.98px) {
    .quarto-title-banner {
        height: 300px;
    }
}
header#title-block-header::before {
    content: "";
    width: 100%;
    height: 80px;
    position: absolute;
    background-color: #eee;
    top: -80px;
}
</style>
```

## Introducere

Inteligen탵a artificial캒 generativ캒 (IA generativ캒) ne poate ajuta s캒 칥mbun캒t캒탵im modul 칥n care realiz캒m diverse sarcini, at칙t 칥n plan personal c칙t 탳i profesional.

Obiectivul acestui workshop este de a sprijini participan탵ii s캒 ia decizii informate cu privire la utilizarea instrumentelor de IA generativ캒.
Participan탵ii vor 칥nv캒탵a c칙nd s캒 foloseasc캒 IA generativ캒, c칙nd s캒 evite utilizarea IA generativ캒 탳i cum s캒 aleag캒 instrumentul optim pentru situa탵ii specifice de lucru.

La finalul workshopului, participan탵ii:

- Vor putea evalua o sarcin캒 de lucru pentru a determina dac캒 IA generativ캒 este solu탵ia potrivit캒, pe baza unor criterii clare precum riscul, acurate탵ea 탳i confiden탵ialitatea.

- Vor putea compara principalele instrumente de pe pia탵캒 (ChatGPT, Gemini, Claude) pentru a alege cea mai bun캒 variant캒 pentru nevoile specifice.

- Vor putea utiliza IA generativ캒 칥n mod informat, responsabil 탳i eficient, at칙t pentru proiecte profesionale, c칙t 탳i personale.

Indiferent dac캒 sunte탵i la 칥nceput de drum sau ave탵i deja experien탵캒, acest workshop v캒 va oferi o metod캒 clar캒 de a integra IA generativ캒 칥n activit캒탵ile zilnice.

Participan탵ii vor dob칙ndi o metod캒 clar캒 de luare a deciziilor pentru interac탵iunea cu IA 탳i vor avea 칥ncrederea necesar캒 pentru a folosi IA generativ캒 칥n mod informat, etic 탳i adaptat nevoilor lor profesionale 탳i personale.

## Link-uri

::: {.lead .fs-3}
游닂 [Workshop: Materiale](content/00_agenda.qmd)
:::
