---
title: "Checklist pentru utilizarea responsabilă IA Generativă"
---

Înainte de a folosi orice instrument de IA Generativă, este bine să reflectați asupra intenției, modului de utilizare și impactului său.

Resursa de mai jos[^1] este o listă de verificare (un instrument de reflecție) menită să vă ajute să faceți o pauză și să gândiți critic înainte de a utiliza instrumentul de IA Generativă ales.

[^1]: Traducere și adaptare după John Smith, Eva Sclippa, Jack Mulvaney, Kristina Bush, Lucy Flamm, Maggie Boyd, and Natalie LoRusso at Boston University. 2025, disponibil la <https://hdl.handle.net/2144/50863> . Distribuit sub licența [CC BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ro)

| Criteriu | Întrebare principală | Întrebări adiționale/<br>de detaliu | Da / Nu / Cu observații | Comentarii / Riscuri identificate |
|---------------|---------------|---------------|---------------|---------------|
| **Utilizare personală/profesională** | Care sunt obiectivele specifice pentru utilizarea IA Generative în această sarcină? | Va fi necesar să poți realiza această sarcină în mod independent (fără IA) pe viitor? |  | Există o alternativă sau o resursă suplimentară care te poate ajuta să rezolvi mai bine sarcina? |
| **Transparență** | Ești pregătit să arăți și să replici modul în care ai utilizat IA Generativă pentru această sarcină? | Ai verificat cu colegii/membrii echipei dacă sunt de acord cu utilizarea ta de IA Generativă? |  | Necesitatea de a documenta prompturile și rezultatele pentru audit sau replicare. |
| **Drepturi de autor (Copyright)** | Intenționezi să păstrezi drepturile de proprietate pentru o idee, date, text scris sau opinie generate? | Folosești, ca date de intrare pentru IA Generativă, informații care sunt protejate prin drepturi de autor? |  | Prin utilizarea ideilor tale ca date de intrare, este posibil să nu mai deții proprietatea intelectuală a conținutului creativ generat. |
| **Confidențialitate** | Ești confortabil/ă ca prompturile tale să fie asociate cu numele și adresa ta de email? | Datele pe care le trimiți ca date de intrare sunt confidențiale? |  | Risc: Este posibil ca instrumentul de IA utilizat să folosească datele introduse pentru antrenament. Nu distribui informații confidențiale! |
| **Consecințe** | Ce s-ar putea întâmpla dacă folosești acest instrument (riscuri, dependență, erori)? | Este utilizarea instrumentelor IA permisă la locul de muncă/școală (conform politicii instituției)? |  | Asigură-te că ai verificat politica de utilizare a IA cu angajatorul/instituția. |
| **Etică & Impact** | Valoarea adăugată a utilizării acestui instrument este mai mare decât impactul negativ potențial (de exemplu, asupra mediului)? | Utilizarea instrumentului de IA pentru această sarcină minimizează importanța expertizei umane sau a creativității? |  | Opțiuni: Poți alege să faci sarcina tu însuți/însăți sau să găsești pe cineva să te ajute. |
| **Etică & Sursă** |  | Câtă energie și apă va consuma această sarcină (consumul de resurse necesare prelucrării datelor)? |  |  |
| **Etică & Sursă** |  | Instrumentul de IA a fost antrenat cu cărți, articole, artă folosite fără permisiune (încălcarea drepturilor de autor la sursă)? |  |  |
| **Acuratețe & Verificare** | Ai încredere în acest instrument? Poți argumenta de ce? | Ai confirmarea că rezultatele nu perpetuează prejudecăți și stereotipuri? |  |  |
| **Acuratețe & Halucinații** |  | Cum știi că instrumentul nu produce informație care nu există (fenomen numit "halucinație")? |  |  |
| **Acuratețe & Calitate** |  | Ai verificat dacă instrumentul va produce informații actuale, precise și de calitate? |  | Acțiune: Verifică de două ori informația pe care instrumentul o oferă ca referință prin accesarea surselor originale. |