---
title: Bine ați venit!
subtitle: "Fundamentele Inteligenței Artificiale Generative"
format: 
  revealjs: 
    theme: [default, "../../styles/_style.scss"]
    width: "1600"
    height: "900"
    slide-number: c/t
    link-external-newwindow: true
    chalkboard: false  
    controls: true
    menu: false

---


## Așteptări legate de workshop

<br>

🎯 **De la acest workshop îmi doresc în special să...**

* Știu când să folosesc (sau nu) IA.

* Înțeleg beneficiile, riscurile și limitele IA.

* Compar diferite instrumente (ChatGPT, Gemini, Claude etc.).

* Descopăr aplicații utile pentru munca mea.

* Aflu bune practici pentru folosirea responsabilă.



## Obiectivul nostru de astăzi

Vom învăța **cum să decidem** în legătură cu IA, nu doar cum să o folosim.

<br>

::: {.columns .small style="margin-top: 2rem;"}
::: {.column width="50%"}
#### Ce **NU** este acest workshop:

<br>

❌ **Un curs tehnic**
<br>
Nu ne vom concentra pe a învăța fiecare funcție pentru un instrument specific.

<br>

❌ **O prezentare teoretică**
<br>
Nu ne vom axa pe teoria complexă din spatele IA.
:::

::: {.column width="50%"}
#### Ce **ESTE** acest workshop:

<br>

✅ **Un ghid pentru decizii**
<br>
Vom învăța un cadru pentru a evalua **când**, **de ce** și **cum** să folosim IA.

<br>

✅ **Un antrenament pentru gândire critică**
<br>
Vom analiza scenarii, vom compara instrumente și vom evalua riscuri pentru a lua decizii informate.
:::
:::



## Agenda {.content-bottom}



| Timp | Subiect |
|:---|:---|
| {{< bi clock >}} 10 min| Introducere și bun venit |
| {{< bi clock >}} 35 min| **Partea I: Fundamente**<br> • Ce este IA generativă?<br> • Când să folosim și când să evităm IA?<br> • Activități practice |
| {{< bi clock >}} 65 min| **Partea a II-a: Instrumente** <br> • Cadru de decizie pentru lucrul cu IA<br> • Activități practice |
| {{< bi clock >}} 5 min| Încheiere |



## La finalul workshopului:

<br>

::: small

✔ **Evaluați când să folosiți IA generativă.**

Veți putea decide dacă IA generativă este potrivită pentru o sarcină, folosind criterii clare precum risc, acuratețe, expertiză, confidențialitate și etică.

✔ **Alegeți instrumentul potrivit.**

Veți putea aplica un cadru de decizie sistematic pentru a selecta instrumentul optim de IA generativă pentru o sarcină specifică.

✔ **Comparați instrumentele de top.**

Veți putea înțelege diferențele de capabilități și performanță între ChatGPT, Gemini și Claude pentru sarcini comune precum sumarizarea, generarea de conținut și asistența tehnică.

✔ **Utilizați IA generativă în mod responsabil.**

Veți putea recunoaște riscurile și veti putea aplica bune practici pentru a colabora eficient și etic cu IA.

:::